version: "3"

services:
  front:
    image: "node:16-alpine3.11"
    volumes:
      - "./front:/home/node/app:rw,consistent"
    working_dir: "/home/node/app"
    command: "yarn start --host 0.0.0.0 --poll 1"
    ports:
      - "3000:3000"
    networks:
      - frontnet

  api:
    image: "node:16-alpine3.11"
    volumes:
      - "./api:/home/node/app:rw,consistent"
    working_dir: "/home/node/app"
    environment:
      PORT: "5000"
      USER_MONGO: "TBD"
      PASS_MONGO: "TBD"
      DBNAME_MONGO: "TBD"
      DOMAIN_MONGO: "TBD"
    command: "yarn start"
    ports:
      - "5000:5000"
    networks:
      - frontnet

networks:
  frontnet:
    driver: bridge
