name: Testing frontend

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      client-dir: ./front

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.15
      uses: actions/setup-node@v1
      with:
        node-version: 14.15
    - name: Install dependencies
      run: yarn install
      working-directory: ${{ env.client-dir }}
    # - name: Lint
    #   run: yarn run lint
    #   working-directory: ${{ env.client-dir }}
    - name: Test
      run: yarn test --watchAll=false
      working-directory: ${{ env.client-dir }} 
